# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - demo-daniel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://demodaniel.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3d9d4cda25f44c689d3d97362dd97eca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_398252f89acb440882055caa5cb4bba9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: demodaniel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3d9d4cda25f44c689d3d97362dd97eca }}/demodaniel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demo-daniel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d3fd218d65e644e9aecc47d9a838d1dc }}
        images: 'demodaniel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3d9d4cda25f44c689d3d97362dd97eca }}/demodaniel:${{ github.sha }}'